### PR TITLE
[api-extractor] Add a new message "ae-undocumented"

### PR DESCRIPTION
**Pull request by octogonz**
## Summary

Requested in [this Zulip thread](https://rushstack.zulipchat.com/#narrow/stream/262521-api-extractor/topic/Expose.20needsDocumentation.20.2F.20undocumented/near/393554244).

Although API Extractor already flags undocumented items in the .api.md file as `// (undocumented)`, @leordev wants to detect them via the `Extractor.invoke()` API for CI validation.

 

## How it was tested

The  `ae-undocumented` message defaults to `logLevel=none`, so I modified a test project to use `logLevel=warning` and confirmed that it is printed correctly.

## Impacted documentation

Need to add this message to the website.

### CODE REVIEW

**Review by D4N14L — APPROVED** [review]

**Comment by leordev** [comment]
This is great, thank you so much for this PR! Testing `ae-undocumented` with `loglevel = warning` against my repo at [this snapshot](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/index.ts) generated my desired outcome report:


**TBDocs Report**

🛑 Errors: 0
⚠️ Warnings: 20

https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/index.ts

| 📄 **File**: [src/docs-generator.ts](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-generator.ts) |
| --- |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "generateDocs". [#L20](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-generator.ts#L20) |

| 📄 **File**: [src/docs-report/index.ts](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/index.ts) |
| --- |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "runDocsReport". [#L12](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/index.ts#L12) |

| 📄 **File**: [src/docs-report/interfaces.ts](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts) |
| --- |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "DocsReporterType". [#L2](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L2) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "DocsGeneratorType". [#L5](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L5) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "DocsReport". [#L8](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L8) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "reporter". [#L9](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L9) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "errorsCount". [#L10](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L10) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "warningsCount". [#L11](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L11) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "messages". [#L12](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L12) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "MessageCategory". [#L16](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L16) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "MessageLevel". [#L19](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L19) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "ReportMessage". [#L22](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L22) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "level". [#L23](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L23) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "category". [#L24](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L24) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "messageId". [#L25](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L25) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "text". [#L26](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L26) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "sourceFilePath". [#L27](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L27) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "sourceFileLine". [#L28](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L28) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "sourceFileColumn". [#L29](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L29) |
| ⚠️ `extractor:ae-undocumented`: Missing documentation for "context". [#L30](https://github.com/TBD54566975/tbdocs/blob/f3084665b16aec32cfbfbe628cfea4636daed281/src/docs-report/interfaces.ts#L30) |

**Review by leordev — APPROVED** [review]
LGTM, worked as intended for my goals and reviewing the code it makes sense to me (but take it with huge grains of salt, since I'm not familiar with the repo). 

Thank you so much for the support on this PR.

**Comment by octogonz** [comment]
@leordev this was released with API Extractor 7.38.0 🚀

**Comment by leordev** [comment]
@octogonz I just realized that this is also warning non exposed members, in my particular case private class members:

- ⚠️ `extractor:ae-undocumented`: Missing documentation for "_metadata".
- ⚠️ `extractor:ae-undocumented`: Missing documentation for "_data". 
- ⚠️ `extractor:ae-undocumented`: Missing documentation for "_signature". 

This is my class definition:
```ts
export class MyClass<T> {
  private _metadata: ResourceMetadata<T>
  private _data: ResourceKindModel<T>
  private _signature: string

  // ...
}
```

Is it possible to set it only for exposed APIs? Maybe through configuration?

**Comment by octogonz** [comment]
> @octogonz I just realized that this is also warning non exposed members, in my particular case private class members:
> 
>     * ⚠️ `extractor:ae-undocumented`: Missing documentation for "_metadata".
> 
>     * ⚠️ `extractor:ae-undocumented`: Missing documentation for "_data".
> 
>     * ⚠️ `extractor:ae-undocumented`: Missing documentation for "_signature".
> 
> 
> This is my class definition:
> 
> ```ts
> export class MyClass<T> {
>   private _metadata: ResourceMetadata<T>
>   private _data: ResourceKindModel<T>
>   private _signature: string
> 
>   // ...
> }
> ```
> 
> Is it possible to set it only for exposed APIs? Maybe through configuration?

This is a bug. It is not intentional behavior.

**Comment by octogonz** [comment]
Here is a fix: https://github.com/microsoft/rushstack/pull/4392

**Pull request merged**
