### PR TITLE
[rush] Fix typo in version-policies.json

### PR DESCRIPTION
**Pull request by no23reason**

### CODE REVIEW

**Comment by iclanton** [comment]
Good catch! We should fix it [here](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/assets/rush-init/common/config/rush/version-policies.json#L8) too.

**Comment by no23reason** [comment]
@iclanton Thanks for the note, I was not aware of the other file, I amended the commit with a fix there a well :)

**Comment by iclanton** [comment]
Looks like a bunch of versions in `package.json`s got bumped. Can you revert those?

You'll also need to run `rush change` to generate a changelog file for the `rush-lib` project.

**Comment by no23reason** [comment]
Sorry about that, I managed to get my repo in some weird shape :-/ it should be fixed now and with the change file as well. I apologize for the complications...

**Comment by octogonz** [comment]
Thanks @no23reason!

**Pull request merged**
