### PR TITLE
Bring 6 more packages under the @rushstack NPM scope

### PR DESCRIPTION
**Pull request by octogonz**
This PR migrates the following packages to use the new `@rushstack` NPM scope:
- `@microsoft/node-core-library`
- `@microsoft/package-deps-hash`
- `@microsoft/stream-collator`
- `@microsoft/ts-command-line`
- `@microsoft/loader-raw-script`
- `@microsoft/set-webpack-public-path-plugin`

In a separate PR, we will retire these two packages:
- `@microsoft/resolve-chunk-plugin`
- `@microsoft/rush-stack`

In a somewhat later future PR, we will migrate these packages to `@rushstack`:
- `@microsoft/rush`
- `@microsoft/rush-lib`
- `@microsoft/api-extractor`
- `@microsoft/api-extractor-model`
- `@microsoft/api-documenter`

For the migrated packages, we are using a SemVer PATCH version bump to make it clear that nothing significant was changed during the rename.

After the migrated packages are published, we will publish "tombstone" MAJOR version bumps of the `@microsoft` packages.   Tombstone releases have a `postinstall` [script](https://github.com/microsoft/rushstack/tree/master/repo-scripts/tombstone) that instructs users how to upgrade.

### CODE REVIEW

**Comment by octogonz** [comment]
NOTE: The root-level README.md inventory is not updated in this PR.  I will update it after the new packages are published.

**Comment by iclanton** [comment]
Are you going to create the tombstones in a separate PR?

**Comment by octogonz** [comment]
> Are you going to create the tombstones in a separate PR?

I think they might be a special job that runs on a special branch.

**Comment by octogonz** [comment]
Tombstone PR is here: https://github.com/microsoft/rushstack/pull/1785

**Comment by octogonz** [comment]
This PR retired `@microsoft/resolve-chunk-plugin` and `@microsoft/rush-stack`: https://github.com/microsoft/rushstack/pull/1786

And this one published their tombstone releases: https://github.com/microsoft/rushstack/pull/1788

**Pull request merged**
