### PR TITLE
[rush] Fix spelling of "committing" in rush.json schema and template

### PR DESCRIPTION
**Pull request by pwbriggs**
## Summary

Fix a spelling error in both the rush.json schema and the rush.json template.

## Details

`commiting` -> `committing`

## How it was tested

N/A

## Impacted documentation

None.

### CODE REVIEW

**Comment by iclanton** [comment]
You need to run `rush change` to generate a changefile.

**Comment by pwbriggs** [comment]
I ran `rush change` on my fork, but it output this message:

```
The target branch is upstream/main
Checking for updates to upstream/main...
No changes were detected to relevant packages on this branch. Nothing to do.
```

**Comment by pwbriggs** [comment]
Oops, sorry, I completely forgot to fill out all the fields in the PR template. Will do.

**Comment by pwbriggs** [comment]
@microsoft-github-policy-service agree

**Comment by iclanton** [comment]
@pwbriggs Ah that's because you committed to your fork's `main` branch, so Rush doesn't know how to compute the diff.

If you run `git add remote microsoft https://github.com/microsoft/rushstack.git` and `git fetch --all`, and then run `rush change` again, it should work. In my clones, I create two remotes: `microsoft` (https://github.com/microsoft/rushstack.git), and `origin` (pointing at my fork) and then I set up my local `main` branch to track the `microsoft` origin (via `git checkout -b main microsoft/main`).

**Comment by pwbriggs** [comment]
Ohhh, I was running `rush change` on the wrong branch 🤦

**Review by iclanton — APPROVED** [review]

**Pull request merged**
