### PR TITLE
[rush] Eliminate keytar dependency

### PR DESCRIPTION
**Pull request by octogonz**
## Summary

Fixes https://github.com/microsoft/rushstack/issues/2492

## Details

This solution was suggested in https://github.com/Azure/azure-sdk-for-js/issues/14346#issuecomment-825995352

> 
> While we wait for v2, if it is indeed the case that rush currently uses only the device code login flow and you do not care about whether the underlying implementation for this uses the newer MSAL or not, then another option for you can be to update the identity dependency to use `~1.0.0` instead of say `^1.0.0`. The `keytar` dependency came into play when we added the VisualStudioCodeCredential in 1.1.0. So, versions 1.0.* should be safe for you to use device code login flow from `@azure/identity`.
> 
> Once we have resolved this issue for native components, you can get right back to using the latest identity package

## How it was tested

1. Confirmed that `keytar` is eradicated from **pnpm-lock.yaml** in this repo

2. @iclanton @elliot-nelson Maybe you could try this in your environment?  I don't have an Azure store set up.

### CODE REVIEW

**Comment by elliot-nelson** [comment]
No luck on my end; checked out branch and I get same build error as the PR build (`"@azure/identity/types/identity"' has no exported member 'AzureAuthorityHosts'`).

**Comment by elliot-nelson** [comment]
From looking at the commit history, it looks like you _could_ have used `v1.0.3` (the last version without keytar) if we weren't supporting Azure environments besides the default (`AzurePublicCloud`).  Since we _do_ support those hosts, like `AzureChina`, `AzureGermany`, etc., we can't use a version without keytar.

**Comment by ramya-rao-a** [comment]
@octogonz, @elliot-nelson  `AzureAuthorityHosts` is just an enum for the different authority hosts we have which does not change that often.

Looks like you are using it as below https://github.com/microsoft/rushstack/blob/0e1d77324a4a92fad63e07d1be813783956ef204/apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts#L23


Can you try changing it to the below until you can move to v2 of Identity?

`export type AzureEnvironmentNames = "AzureChina" | "AzureGermany" | "AzureGovernment" | "AzurePublicCloud";` 

If that does not work, you can also copy over the enum from 
https://github.com/Azure/azure-sdk-for-js/blob/887eb013a7c9278b7eedb2c04c5e1bac0b984ebe/sdk/identity/identity/src/constants.ts#L22-L39

**Comment by octogonz** [comment]
We're also having an issue where this code:
https://github.com/microsoft/rushstack/blob/0e1d77324a4a92fad63e07d1be813783956ef204/apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts#L303-L310
no longer compiles because the older signature was:
```ts
export declare class DeviceCodeCredential implements TokenCredential {
    /**
     * Creates an instance of DeviceCodeCredential with the details needed
     * to initiate the device code authorization flow with Azure Active Directory.
     *
     * @param tenantId The Azure Active Directory tenant (directory) ID or name.
     *                 'organizations' may be used when dealing with multi-tenant scenarios.
     * @param clientId The client (application) ID of an App Registration in the tenant.
     * @param userPromptCallback A callback function that will be invoked to show
                                 {@link DeviceCodeInfo} to the user.
     * @param options Options for configuring the client which makes the authentication request.
     */
    constructor(tenantId: string | "organizations", clientId: string, userPromptCallback: DeviceCodePromptCallback, options?: TokenCredentialOptions);
```

**Comment by ramya-rao-a** [comment]
@octogonz Yes, that would be correct. The parameters to DeviceCodeCredential were made to be optional in 1.2.0
Relevant changelog entry is in https://github.com/Azure/azure-sdk-for-js/blob/%40azure/identity_1.3.0/sdk/identity/identity/CHANGELOG.md#changes-since-the-latest-12-beta

> DeviceCodeCredential now has both of its constructor parameters, tenantId and clientId, as optional parameters. The default value of tenantId is "organizations", and the Azure CLI's client ID is the default value of clientId.

**Comment by elliot-nelson** [comment]
I used our existing (testing) azure storage cloud branch to test this in the local monorepo, using the following command for testing:

```
node [PATH_TO_RUSHSTACK]/apps/rush-lib/lib/start.js build -v --to [PACKAGE_NAME]
```

✅ [rushstack] Checked out `master`, `rush install && rush build`
✅ [hbo] Touched file & built, checked cloud cache and set cloud cache successfully

✅ [rushstack] Checked out `octogonz/rush-eliminate-keytar`, `rush install && rush build`
✅ [rushstack] Confirmed: `@azure/identity@1.0.3` and no sign of `keytar`
✅ [hbo] Built our monorepo: success
✅ [hbo] Touched file & built, checked cloud cache and set cloud cache successfully
✅ [hbo] Ran `rush update-cloud-credentials` and followed Device Login flow: success
✅ [hbo] Touched file & built, checked cloud cache and set cloud cache successfully

Based on these steps, it seems like the package without keytar is doing what it's supposed to.

**Comment by octogonz** [comment]
Awesome, thanks @elliot-nelson!!

**Comment by octogonz** [comment]
This fix was released with Rush 5.46.0

**Comment by ramya-rao-a** [comment]
yay!

**Pull request merged**
