### PR TITLE
Bump builds up to use Node 12, and add support for Node 14.

### PR DESCRIPTION
**Pull request by iclanton**
As per https://nodejs.org/en/about/releases/:
- Node 8 is no longer LTS
- Node 10 is Maintenance LTS
- Node 12 is Active LTS
- Node 14 will be the upcoming Active LTS

In the past, we've the active LTS version of Node in addition to the maintenance LTS version and the upcoming version. This PR drops support for Node 8 and adds support for Node 14.

Note: we may want to consider updating [this](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/logic/NodeJsCompatibility.ts#L43) as well

### CODE REVIEW

**Comment by octogonz** [comment]
Could we maintain Node 8 support for another month or two? My company has a repo that has not finished upgrading from Node 8 yet, and it consumes some Rush Stack packages.

**Comment by iclanton** [comment]
@octogonz - Sure that sounds fine. I added support for Node 8 back.

Our use of Mocha doesn't seem to play nice with Node 14, so I've disabled Mocha for projects without unit tests and converted the remaining projects to use Jest.

**Comment by octogonz** [comment]
> Our use of Mocha doesn't seem to play nice with Node 14, so I've disabled Mocha for projects without unit tests and converted the remaining projects to use Jest.

I have a longstanding soapbox that we should not be reporting an error for projects without unit tests.  The person should not have to edit a config file to disable the test runner, just because they haven't written any tests.  

If I remember right, requiring at least one test was the default behavior of Mocha (and maybe Jest too), but it is a poor design particularly for a standardized toolchain that is shared across monorepo projects.

**Comment by iclanton** [comment]
Agreed on the tests. I'd like to replace the whole test runner soonish, perhaps as a bigger tooling overhaul.

**Pull request merged**
