### PR TITLE
Adds a failing pnpm unit test for package installation

### PR DESCRIPTION
**Pull request by KevinGrandon**
Refs #1116

### CODE REVIEW

**Comment by halfnibble** [comment]
I think it would make sense to assign this PR to @sachinjoseph 
@iclanton  Can we add him to this repo?

**Comment by octogonz** [comment]
@halfnibble this PR does not solve https://github.com/microsoft/web-build-tools/issues/1116.  It merely adds a unit test case; it does not actually implement support for GitHub URLs as package versions.

In https://github.com/microsoft/web-build-tools/issues/1116#issuecomment-469087986 I made a case that GitHub URLs are not a particularly wise feature.  If someone implemented it, we would accept it, but there's much more important issues to work on.

**Comment by halfnibble** [comment]
I agree that GitHub URLs should not be part of a production release. However, I have had occasion to use the `pip` equivalent of this in the past.

For example: a large, popular open source library with one tiny bug that only affects my particular edge case and the owners are slow to respond. The options are to create a new repo that I will maintain, wait and hope the original maintainers will eventually accept my PR, or just fix it now and hope I can someday get rid of the URL dependency and switch back to the main library once my PR is evaluated. 

I think this could also be useful for testing multiple repos that a developer owns—or they could just switch to using a mono repo... ;-)

**Comment by octogonz** [comment]
Closing because there has been no activity for a long time. If you want to pursue this, please open a new PR. Thanks!

**Pull request closed without merging**
