### PR TITLE
[api-extractor] Allow omission of import statements in API reports

### PR DESCRIPTION
**Pull request by Josmithr**
## Summary

Add a config option for omitting import statements from API reports.

## Details

Especially when combined with the new `reportVariants` functionality, the import statements included in the reports by default may or may not actually reflect the set of imports used by the (reduced) set of exports included in the report.

Additionally, for reviewing / API change monitoring, including the import statements can create unwanted noise in PR reviews.

The new `includeImports` report config option is optional, and defaults to `true` to preserve existing behavior. 

## How it was tested

Updated one of the test suite configurations to omit imports. See updated test collateral.

## Impacted documentation

This page may want to be updated to call out the new optional config parameter:
https://api-extractor.com/pages/setup/configure_api_report/

### CODE REVIEW

**Comment by WayneFerrao** [comment]
Nit: Spelling in title  'omission'?

**Comment by Josmithr** [comment]
Related: https://github.com/microsoft/rushstack/issues/4762

**Comment by octogonz** [comment]
> Related: #4762

How are these related?  #4762 seems to be an actual bug which would affect .d.ts rollups as well.

**Comment by Josmithr** [comment]
> > Related: #4762
> 
> How are these related? #4762 seems to be an actual bug which would affect .d.ts rollups as well.

This was an error on my part. Linked from the wrong ticket. Please disregard 😅

**Comment by Josmithr** [comment]
Superseded by #4861. Closing this.

**Pull request closed without merging**
