### PR TITLE
[heft] Update node-sass to support node 15.

### LINKED ISSUE #2490: [heft] Update node-sass dependency to 5.0.0 in order to fix builds with Node 15
Installing heft on Linux with Node 15 doesn't work - I get the following errors:

```bash
.../node_modules/node-sass install$ node scripts/install.js
../node_modules/node-sass install: Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node
.../node_modules/node-sass install: Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node": 
.../node_modules/node-sass install: HTTP error 404 Not Found
.../node_modules/node-sass install: Hint: If github.com is not accessible in your location
.../node_modules/node-sass install:       try setting a proxy via HTTP_PROXY, e.g. 
.../node_modules/node-sass install:       export HTTP_PROXY=http://example.com:1234
.../node_modules/node-sass install: or configure npm proxy via
.../node_modules/node-sass install:       npm config set proxy http://example.com:8080
.../node_modules/node-sass install: Done
```

This can be fixed by bumping the dependency of node-sass to 5.0.0, which has releases for Node 15.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@rushstack/heft` version? | 0.24.2 |
| Operating system? | Linux |
| Would you consider contributing a PR? | Yes |
| Node.js version (`node -v`)? | 15.8.0 |

### PR DESCRIPTION
**Pull request by halfnibble**
## Summary

Update node-sass to support Node 15.

## Details

Fixes #2490
Note: Loses heft sass support for Node versions 8, 11, and 13.

## How it was tested

Tested with build-tests/heft-sass-test

### CODE REVIEW

**Comment by chengcyber** [comment]
Kind of curious about whether it is possible to use `sass` (Dart Sass) package instead of `node-sass`. Since `node-sass` has been deprecated.

**Comment by halfnibble** [comment]
> Kind of curious about whether it is possible to use `sass` (Dart Sass) package instead of `node-sass`. Since `node-sass` has been deprecated.

Probably. Last time I tried dart sass it was about 3x slower than libsass. I've actually mulled the idea of forking node-sass and creating my own open source library. There are some features I want in Sass that the maintainers don't seem too keen on. But alas, I doubt I have the time.

**Comment by dmichon-msft** [comment]
There's a recommendation that Dart Sass is faster than `node-sass` if you get the version that runs the Dart VM, but that one doesn't ship as an npm package.

**Comment by xc2** [comment]
How about using `sass@npm` instead of `node-sass@npm` in rushstack by default, and providing options for user to  specific render function or sass package.

**Comment by halfnibble** [comment]
> How about using `sass@npm` instead of `node-sass@npm` in rushstack by default, and providing options for user to specific render function or sass package.

We are going to refactor this Heft plugin and make the entire sass plugin both optional (many node projects don't need Sass) and configurable. I'll create a separate issue to track that endeavor. As a quick fix, however, I will get this version bump in as is.

**Review by iclanton — APPROVED** [review]

**Pull request merged**
