### PR TITLE
[rush] WIP: Add pre and post build processes. re: #830

### PR DESCRIPTION
**Pull request by halfnibble**
Implement pre and post npm scripts.

I'm not sure how feasible it is to mock the subsequent executions (e.g. test build after prebuild completes). So any feedback on how to do this would be nice.

This appears to be working for me, but I don't have a real world application to test it on.

### CODE REVIEW

**Comment by wbern** [comment]
This will likely be a breaking change for many users.

Would it be possible to add in a command line parameter that lets you choose whether it should be on or not?

I could live with not having the option, but it might trip some people up.

**Comment by halfnibble** [comment]
I realize this isn't incremental for pre and post build steps. I'm now investigating PR #1403 to see if that will allow pre and post to work incrementally. 

DO NOT MERGE.

**Comment by aliatsis** [comment]
@halfnibble is there any hope for this getting merged any time soon?

**Comment by anonrig** [comment]
This seems like a really good feature.

**Comment by iclanton** [comment]
This would be better accomplished with a phased build.

**Pull request closed without merging**
