### PR TITLE
[rush-lib]  Add optional 'commonFolder' configuration setting to control the common folder location

### PR DESCRIPTION
**Pull request by fearthecowboy**
Discussion started with @octogonz  in gitter -- created discussion here: https://github.com/microsoft/rushjs.io-website/issues/36

This PR contains the proposed changes to support `commonFolder` as a configuration in `rush.json`

### CODE REVIEW

**Comment by wolfd** [comment]
I like the idea of this, being able to move the common folder elsewhere would have been an easier bullet to bite when I was first setting up rush. You may want to change how the `install-run.js` script works though.
https://github.com/microsoft/web-build-tools/blob/04c736daed365bc4b774656a8120cf71ae42e383/common/scripts/install-run.js#L337

I do see the point of having one common `common` folder for all rush repos, to make it easier to start working on a project if you knew rush already. However, there are enough monorepos out there that might use the `common` folder for something else.

**Comment by octogonz** [comment]
I'm open-minded about this.  

However, when developers move between Rush repos, it's very valuable to have a familiar directory layout that helps you understand how the project is structured.  In some situations that can make it harder to set up Rush; but the everyday usage experience is more important than the one time setup experience.

If the `common` folder design has genuine downsides (as called out in https://github.com/microsoft/rushjs.io-website/issues/36) such that multiple people are wanting to change it, then I'd first want to consider whether we can improve the out-of-box design.  Renaming such a central fixture of the Rush repo will certainly be disruptive.  But if it's a significant improvement, it may be worth it.

@iclanton

**Comment by octogonz** [comment]
I opened https://github.com/microsoft/web-build-tools/issues/1511 to discuss.

**Comment by iclanton** [comment]
I don't think we're going to pursue making this configurable anytime soon, so I'm going to close this PR. We may consider revisiting this in a later major version of Rush.

**Pull request closed without merging**
