### PR TITLE
[rush] Fix an issue where the "usePnpmFrozenLockfileForRushInstall" experiment sometimes caused installs to fail

### PR DESCRIPTION
**Pull request by D4N14L**
Prior to running `rush install`, Rush validates that install should be allowed depending on the state package dependencies and their status in the `pnpm-lock.yaml` file. This prevents `rush install` from being run in cases where the version does not match the version in the lockfile. Local dependencies however are handled entirely by Rush by placing them into a `rushDependencies` field in the `common/temp/projects` package.json. This means that a change that adds an existing local dependency or manually bumps a local dependency version is not validated against the lockfile (since the lockfile does not contain this data), but is instead validated by checking that the local dependency can be satisfied, we and fail if this isn't the case.

This causes an issue when using frozen-lockfile, as the hash contained in the lockfile cannot be modified unless running `rush update`. If a `rushDependency` is modified, the hash of the resulting tarball will change while the contents of the lockfile will not. This difference will cause install to fail in the case where the hash in the lockfile does not match the hash of the tarball. Without frozen-lockfile, this issue does not exist because PNPM will update the hash of the `common/temp` lockfile to match as it resolves packages (a step which is skipped when using frozen-lockfile).

The proposed PR makes it such that the hash contained in the `common/temp` lockfile always matches the hash of the generated tarball. Changes to non-local packages should still cause `rush install` to fail prior to running PNPM due to the validation that is performed before an install is kicked off. This is entirely to allow PNPM to avoid the `hash does not match` errors that are produced when manually modifying local dependency specifiers.

### CODE REVIEW

**Comment by octogonz** [comment]
The code looks okay, but @D4N14L I have no idea what problem this is solving, or how it fixes the problem. Could you provide a PR description? 😋

**Comment by sachinjoseph** [comment]
> 
> 
> The code looks okay, but @D4N14L I have no idea what problem this is solving, or how it fixes the problem. Could you provide a PR description? 😋

@octogonz As I understand it, this PR updates the temp shrinkwrap hash of a local tarball if a package json has only changed by its version number and/or a the versions of local package dependencies so that `pnpm install --frozen-lockfile` can succeed. CC: @D4N14L

**Comment by D4N14L** [comment]
> > The code looks okay, but @D4N14L I have no idea what problem this is solving, or how it fixes the problem. Could you provide a PR description? 😋
> 
> @octogonz As I understand it, this PR updates the temp shrinkwrap hash of a local tarball if a package json has only changed by its version number and/or a the versions of local package dependencies so that `pnpm install --frozen-lockfile` can succeed. CC: @D4N14L

@octogonz @sachinjoseph added a description, hopefully that clears it up! Sorry, I didn't realize how out-of-context this change was without a description :(

**Comment by sachinjoseph** [comment]
> 
> 
> Prior to running `rush install`, Rush validates that install should be allowed depending on the state package dependencies and their status in the `pnpm-lock.yaml` file. This prevents `rush install` from being run in cases where the version does not match the version in the lockfile. Local dependencies however are handled entirely by Rush by placing them into a `rushDependencies` field in the `common/temp/projects` package.json. This means that a change that adds an existing local dependency or manually bumps a local dependency version is not validated against the lockfile (since the lockfile does not contain this data), but is instead validated by checking that the local dependency can be satisfied, we and fail if this isn't the case.
> 
> This causes an issue when using frozen-lockfile, as the hash contained in the lockfile cannot be modified unless running `rush update`. If a `rushDependency` is modified, the hash of the resulting tarball will change while the contents of the lockfile will not. This difference will cause install to fail in the case where the hash in the lockfile does not match the hash of the tarball. Without frozen-lockfile, this issue does not exist because PNPM will update the hash of the `common/temp` lockfile to match as it resolves packages (a step which is skipped when using frozen-lockfile).
> 
> The proposed PR makes it such that the hash contained in the `common/temp` lockfile always matches the hash of the generated tarball. Changes to non-local packages should still cause `rush install` to fail prior to running PNPM due to the validation that is performed before an install is kicked off. This is entirely to allow PNPM to avoid the `hash does not match` errors that are produced when manually modifying local dependency specifiers.

@D4N14L Will the install fail if the version of a cyclic dependency changes?

**Comment by D4N14L** [comment]
> @D4N14L Will the install fail if the version of a cyclic dependency changes?

@sachinjoseph yes. These are classed as external dependencies and will be validated like the others

**Comment by octogonz** [comment]
I was concerned that this PR is modifying PNPM's `common/temp` lockfile after it is written, which could be impacted by future changes to the file format. However @D4N14L pointed out that this code path will disappear once we move to `useWorkspaces` in the future.

**Pull request merged**
