### PR TITLE
[api-documenter] feat: Marking optional properties on interface references

### LINKED ISSUE #2269: [api-documenter] Indicate optional members in interface declarations
- [X] Feature
- [ ] Bug

Markdown generated for interfaces do not contain any information about which members are optional. For example, given the following interface:

```typescript
interface Foo {
  a: string;
  b?: string;
}
```

api-documenter will generate the following markdown:

## Properties (actual)

|  Property | Type | Description |
|  --- | --- | --- |
|  a  | string |  |
|  b | string | |

Note that there's no indication that `b` is optional. It would be nice to include this information in the generated markdown docs. Perhaps the easiest would be to list the optional fields with the `?` sign so that the above property gets listed as `b?`. Alternatively it could be included in the property description too.

## Properties (proposed)

|  Property | Type | Description |
|  --- | --- | --- |
|  a  | string |  |
|  b? | string | **Optional** |

I've noticed that this information is missing in the generated doc model file too. It's only available as part of the excerpt tokens:

```
{
  "kind": "PropertySignature",
  "docComment": "...",
  "excerptTokens": [
    {
      "kind": "Content",
      "text": "b?: "
    },
    {
      "kind": "Content",
      "text": "string"
    },
    {
      "kind": "Content",
      "text": ";"
    }
  ],
  "releaseTag": "Public",
  "name": "b",
  "propertyTypeTokenRange": {
    "startIndex": 1,
    "endIndex": 2
  }
}
```

### PR DESCRIPTION
**Pull request by hiranya911**
Indicating optional properties on property tables generated for classes and interfaces. Resolves #2269 

I'm peeking into the first excerptToken of each property signature to see if it's optional. Please let me know if there's a better way, and I'm happy to update.

Sample output:

Screen Shot 2020-10-13 at 3 00 10 PM

### CODE REVIEW

**Comment by octogonz** [comment]
@hiranya911 Thanks for making this PR.  I pushed a commit that adds a test case and replaces your syntax check here...
```ts
  private _isOptionalProperty(property: ApiPropertySignature): boolean {
    return property.excerptTokens[0].text.endsWith('?: ');
  }
```
...with a proper `api-extractor-model` API.

However, I realized that other TypeScript constructs can be optional.  For example, apparently class members [can be optional](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#optional-class-properties).  Also interface methods can be optional.  But `ApiConstructSignature` and `ApiIndexSignature` apparently cannot be optional.

So when I get a little more time I'd like to:
- Figure out the complete set of `ApiItems` that can be optional, and apply `isOptional` to them
- Decide which of these cases are actually useful to mark as `(Optional)` in the generated documentation.  For example maybe optional class members are a shorthand for `| undefined`, but calling them "optional" would not be meaningful to people using the API.

Let me know if you have any thoughts on that.

**Comment by octogonz** [comment]
We could also implement this feature for YamlDocumenter.ts.

**Comment by hiranya911** [comment]
Thanks @octogonz. The changes you've pushed look good. Thanks for adding the `isOptional` property from the API model. I figured there'd be a better way than what I'd come up with.

I think what you've suggested above makes sense: `(Optional)` for interface methods, and `| undefined` for class members. Another item to consider is optional function/method arguments:

```typescript
function foo(arg1: string, arg2?: string) {

}
```

It seems more meaningful to mark `arg2` as `(Optional)` for the above example.

Do you think we should get to all these cases in this PR, or try to address them in a series of future PRs?

**Comment by octogonz** [comment]
> I think what you've suggested above makes sense: `(Optional)` for interface methods, and `| undefined` for class members. Another item to consider is optional function/method arguments:

I think it's important enough metadata that we might as well include it the JSON file.  

However I'm not sure whether we should render it in our documentation.  In TypeScript if a parameter is optional, so must be all subsequent parameters.  Thus it seems pretty easy to figure this out from looking at the signature.

So the parameter table might get more cluttered with `(Optional` in there:

----
<b>Signature:</b>

```typescript
doSomething(a: string, b: string, c?: string, d?: string, e?: string, f?: string);
```

## Parameters

|  Parameter | Type | Description |
|  --- | --- | --- |
|  a | `string` | The first parameter |  |
| b| `string`  | The second parameter |  |
|  c | `string` | (Optional) The third parameter |  |
|  d | `string` | (Optional) The fourth parameter |  |
|  e | `string` | (Optional) The fifth parameter |  |
|  f | `string` | (Optional) The sixth parameter |  |
----

🤔 I don't have a strong opinion, though.

**Comment by octogonz** [comment]
I'm also wondering whether we need BOTH the `?` name suffix AND the `(Optional)` description prefix.

@rbuckton @AlexJerabek @acchou Do you guys have any opinion about how to format optional properties/parameters?

**Comment by acchou** [comment]
I'm in favor of having both. Having only the ? is a bit subtle, especially if you're only reading the Description.

**Comment by AlexJerabek** [comment]
@octogonz I think the `?` is sufficient, but the extra `(Optional)` doesn't bother me.

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
This was released with API Extractor 7.12.0 / API Documenter 7.11.0

**Pull request merged**
