### PR TITLE
[gcb-serve] Add serve.json options for launching default browser and additional apps

### LINKED ISSUE #1338: [gulp-core-build-serve] Option to launch custom browser
I recently started using the SharePoint Framework and ran into a small annoyance: the gulp serve task launches the OS default browser with no option to change it. I figured out that you can add something like this in the gulpfile:

```typescript
...

const gulpOpen = require('gulp-open');

 // Create a subtask to launch a browser session using gulp-open
 let launchBrowserSubTask = build.subTask('launch-browser-subtask', function(gulp, buildOptions, done) {
   // Check if the serve task was invoked by checking args, hope there's a better way to do this!
   if (buildOptions.args._[0] === 'serve') {
     return gulp.src('')
       .pipe(gulpOpen({
         app: 'chrome',
         uri: "https://localhost:5432/workbench"
       }));
   }
   done();
 })
 // add the subtask as a post build task
 build.rig.addPostBuildTask(launchBrowserSubTask);

 build.initialize(gulp);
 ```

 but I think adding the option to the serve.json file would be better, including a no browser option too while we're at it. This means changing the serve.schema.json and unfortunately also spfx-serve.schema.json which is not open as far as I can see. Is it possible to get this updated?
I have made the changes locally, should I create a draft pull request for it?

### PR DESCRIPTION
**Pull request by timdw**
Fixes #1338 

All OK except during testing I found that double quotes in arguments get escaped with a backslash and the whole argument surrounded with double quotes. Not sure if this is just a problem for Windows - maybe it would be desirable on other platforms. Setting this block in serve.json
````JSON
  "launchApps": [
    {
      "app": "chrome",
      "args": ["--profile-directory=\"Profile 1\""]
    }
  ]
````
lead to this command being used to start the process:

`cmd /c start "\"\"" /b chrome "--profile-directory=\"Profile 1\"" https://localhost:5432/workbench`

This failed to launch chrome with the profile, without the extra quotes and escaping it works fine.

I had to use Process Monitor to see what was going on as I think it's Node native code doing this, maybe process_wrap.cc but I can't follow it well enough to be sure.

A workaround for this is to have a .cmd file in the project folder, luckily the current directory is used for the child process.
````JSON
  "launchApps": [
    {
      "app": "launchMyStuff.cmd"
    }
  ]
````
launchMyStuff.cmd:
``start chrome --profile-directory="Profile 1" %1``

### CODE REVIEW

**Comment by iclanton** [comment]
I think adding the ability to launch an arbitrary application is too much complexity. What about something like this:

```TypeScript
export interface IServeTaskConfig {
  ...

  /**
   * If specified, launch the specified browser instead of the OS default browser.
   * If this option is omitted, the system default browser is used.
   */
  browserToOpen?: {
    /**
     * The name of the browser to open. Supported values are:
     * - FIGURE THIS OUT
     */
    name: string;

    /**
     * If specified, supply these arguments before the URL argument when launching the browser.
     */
    additionalArgs?: string[];
  };
}
```

Do you think there's a strong need to open multiple browsers?

**Comment by octogonz** [comment]
> All OK except during testing I found that double quotes in arguments get escaped with a backslash and the whole argument surrounded with double quotes. Not sure if this is just a problem for Windows - maybe it would be desirable on other platforms.

NodeJS is not very good at executing a process correctly.  Most likely your code here ends up invoking one of the broken APIs:
```
        gulp.src('')
            .pipe(open({
              app: app,
              uri: uri
            }));
```
Try this instead:
```
child_process.spawnSync('chrome', ['--profile-directory="Profile 1"'], 
  { windowsVerbatimArguments: true });
```

Another valid approach might be to simplify the quoting, since for Chrome your inner quotes are probably redundant (given the outer quotes):
```
spawnSync('chrome', ['--profile-directory=Profile 1']);
```

These approaches work because we know in advance that Chrome is /not/ a batch file, and thus does not need to be invoked via a shell.  If you want to correctly execute an arbitrary command (that may or may not be a batch file), you'll fall into the fascinating rabbit hole of **node-core-library**'s [Executable API](https://github.com/microsoft/web-build-tools/blob/178f6a99a4bf3dc2f2ee52a60f1539066cce244f/libraries/node-core-library/src/Executable.ts#L113).  On Windows it is only partially solvable, because after NodeJS and the shell each take a turn screwing up any special characters, the final step is for the EXE process itself to parse the arguments out of a single string using a C runtime library, of which there are multiple possibilities -- _each with its own quoting rules_.  I spent an entire overseas plane flight tinkering with that problem haha.

**Comment by timdw** [comment]
@iclanton Originally I did just a single launch, but then I thought why not multiple? The classic use case is to check functionality and appearance between different browsers. For SharePoint though there's the need to test while logged in as different users which can be done in some browsers using profiles.
Creating an enum of supported browsers has the issue that the specific executables vary across platforms - I discovered this reading the [gulp-open README](https://github.com/stevelacy/gulp-open/blob/master/README.md) - so has a potential maintenance overhead. A further example is 32/64 bit install folders as not all browsers are available on the path.
The option for `launchDefaultBrowser` is in case you don't want a browser to launch at all. At the moment the default is to launch unless a command line option is provided. Personally I prefer it as a configuration option.

@octogonz The rabbit hole radar was triggered many times! Making the same configuration work cross platform is not something I wanted to get sucked into which is why I stuck with gulp-open. I hoped people would at least be familiar with it, warts and all!  I just tested removing the quotes around the profile and you're right - it worked. At least for chrome … tried it with firefox and no joy with this:
````JSON
    {
      "app": "C:\\Program Files\\Mozilla Firefox\\firefox.exe",
      "args": ["-P Profile 2"]
    }
````
Firefox [command line options](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options) says that parameters with spaces must be enclosed in quotes.

So the choice seems to be either a pre-defined list or letting people sort it out themselves. Any other ideas? Leave it as it is with the default browser?

**Comment by octogonz** [comment]
Closing because there has been no activity for a long time. If you want to pursue this, please open a new PR. Thanks!

**Pull request closed without merging**
