### PR TITLE
[rush] Update "rush scan" to add "--json" and "--all" flags

### PR DESCRIPTION
**Pull request by chengcyber**
## Summary

Fixes https://github.com/microsoft/rushstack/issues/2450

Add --json --diff flag to `rush scan` command

### CODE REVIEW

**Comment by octogonz** [comment]
@chengcyber Thanks for making this PR!

The parameter name `--diff` seemed slightly misleading, since it suggests a Git operation.  I actually think that your report is more useful than the current `rush scan` behavior.  So I'd like to suggest redesigning the `rush scan` behavior.  Lemme see if I can write up a suggested spec.

**Comment by octogonz** [comment]
I posted a note here: https://github.com/microsoft/rushstack/issues/2450#issuecomment-771971894

**Comment by chengcyber** [comment]
hi @octogonz, could you kindly take another look~ changes are applied in this PR

**Review by octogonz — APPROVED** [review]

**Comment by octogonz** [comment]
@chengcyber Looks good! I made a small improvement to the formatting.

**Comment by octogonz** [comment]
This was published with Rush 5.44.0

**Pull request merged**
