### PR TITLE
[api-extractor] add support for cts and mts

### LINKED ISSUE #3116: [api-extractor] Support .d.mts for documentation and rollups
## Summary

I've been messing around with compiling typescript to `.mjs` and ran into some issues with the rollups/api extraction features:

```
$ npx api-extractor run --local --diagnostics
api-extractor 7.19.2  - https://api-extractor.com/

Using configuration from ./api-extractor.json

ERROR: Error parsing ./packages/foo/api-extractor.json:
The "mainEntryPointFilePath" value is not a declaration file: ./packages/foo/dist/index.d.mts
```

## Repro steps

1. Create a simple typescript project.
2. Instead of using `.ts` files, name them as `.mts`.
3. When compiled, these will result in `.mjs`, `.d.mts` and appropriate map files.
4. Attempt to run api-extractor on the results.

  **Expected result:** API extractor will work as normal.

  **Actual result:** The filename fails validation - I'm not sure if this runs deeper, but the actual contents hasn't seemed to change, other than `import`s/`export`s will all refer to `./foo.mjs` instead of `./foo`.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/api-extractor` version? | 7.19.2 |
| Operating system? | Arch Linux |
| API Extractor scenario? | reporting and rollups |
| Would you consider contributing a PR? | Potentially, if just the filename validation needs updating |
| TypeScript compiler version? | 4.5.4 |
| Node.js version (`node -v`)? | 16.13.1 |

### PR DESCRIPTION
**Pull request by michaelfaith**
Since TS 4.7, two new type declaration extensions have been supported:
- `.d.cts` for types from a compilation on `.cts` files
- `.d.mts` for types from a compilation on `.mts` files

Support has been added for both of these type declarations.  I also included two new test packages,
demonstrating the full `.cts` -> `.cjs`/`.d.cts` and `.mts` -> `.mjs`/`.d.mts` workflow

Fixes #3116

### CODE REVIEW

**Comment by michaelfaith** [comment]
@microsoft-github-policy-service agree

**Comment by michaelfaith** [comment]
Resolved `repo-state` conflict

**Comment by ryanbas21** [comment]
This would be great since there are dts plugins that rely on api extractor and this could really help those of us who publish dual module system packages and need to provide typings for two modules

**Comment by michaelfaith** [comment]
@octogonz any feedback on this change?

**Comment by octogonz** [comment]
I am on vacation, will be back next week

**Comment by michaelfaith** [comment]
Hi @octogonz, are you still going to be looking at this?

**Comment by octogonz** [comment]
This PR was superseded by https://github.com/microsoft/rushstack/pull/4023, but the test cases are useful, so we'll accept it anyway. 😄 
@iclanton

**Review by octogonz — APPROVED** [review]

**Pull request merged**
