### PR TITLE
[heft-jest-plugin] Upgrade to Jest 26

### PR DESCRIPTION
**Pull request by jonasb**
## Summary

Upgrade Jest dependency to 26

## Details

The driver for updating Jest for me is to get the [improved fake timers](https://jestjs.io/blog/2020/05/05/jest-26). AFAICT this works well. I've tried to upgrade to Jest 27 as well but have run into some issues, so creating this PR for now.

If someone wants to have a look at Jest 27 the WIP branch is here: https://github.com/jonasb/rushstack/tree/jest-27

## How it was tested

* `rush build`

### CODE REVIEW

**Comment by dmichon-msft** [comment]
When testing locally I encountered substantial performance degredation when upgrading from Jest 25 -> 26 (or 27), on the order of 40%. Something to check for and see if we can mitigate.

**Comment by elliot-nelson** [comment]
FWIW, on my MacBook, `rush-lib` unit tests run in ~30 seconds on Jest 25.4 and ~28 seconds on Jest 26.6.  That's averaging a few passes in a row for each, but of course isn't particularly scientific.

It seems like a bummer to delay an upgrade of a core lib like Jest, but 40% is a concerning number.  I wonder if that comes up for certain types of unit tests or expectations that aren't present in rush-lib.

**Comment by dmichon-msft** [comment]
Hm, probably need to check my numbers again. I went from 25 all the way to 27 and had noticed some regression, that got worse when I rolled back to 26, but it may be heavily correlated with specific details of how the jest project is configured. I've been doing my best to eliminate babel-jest (and transformations in general) in projects I manage, since that tends to be the largest expense of the load time.

**Comment by iclanton** [comment]
Supplanted by https://github.com/microsoft/rushstack/pull/3076

**Pull request closed without merging**
