### PR TITLE
[Rush] Recreate tarballs if (npm/pnpm/yarn) install is actually run

### PR DESCRIPTION
**Pull request by sachinjoseph**

### CODE REVIEW

**Comment by octogonz** [comment]
@sachinjoseph is this change going to require `rush update` for every single package.json edit?

**Comment by sachinjoseph** [comment]
> @sachinjoseph is this change going to require `rush update` for every single package.json edit?

No, it just regenerates tarballs each time so that any existing local tarballs which were generated by older versions of rush won't cause `pnpm install --frozen-lockfile` to fail with sha mismatch.

**Comment by sachinjoseph** [comment]
@iclanton FYI

**Comment by sachinjoseph** [comment]
> @sachinjoseph Have you tested this thoroughly? If so, do you want me to publish it? This week we've been doing some patch releases for the new "rush deploy" feature.

No, I haven't tested this well enough. Please give me some time until I can validate this.

**Comment by iclanton** [comment]
Should we only regenerate if `--frozen-lockfile` is enabled?

**Comment by sachinjoseph** [comment]
> Should we only regenerate if `--frozen-lockfile` is enabled?

No. I have changed it to regenerate tarballs only if Rush decides to actually run npm/pnpm/yarn install. Creating tarballs is superfast and does not have side effects.

**Comment by sachinjoseph** [comment]
> > @sachinjoseph Have you tested this thoroughly? If so, do you want me to publish it? This week we've been doing some patch releases for the new "rush deploy" feature.
> 
> No, I haven't tested this well enough. Please give me some time until I can validate this.

@octogonz I have tested this on a few repos and have ensured that rush install works as expected.

**Comment by octogonz** [comment]
Published with Rush 5.24.4

**Pull request merged**
