### PR TITLE
[rush-lib] Execute pre-commit hooks during changelog creation commit

### PR DESCRIPTION
**Pull request by manrueda**
## Summary

Currently the pre-commit hooks are not being executed during the commit after the creation of the changelogs files and update of `package.json`. This creates a problem when the files created by Rush do not follow the same code formatting and linting rules as the one used by the project, normally we have a prettier and/or linter on the pre-commit hook to auto-fix this auto generated files. But are not being executed.

With this change, the pre-commit hooks will be executed during the versioning and publish process.

## Details

By default the `--no-verify` flag will not be sent to the `git commit` command.

## How it was tested

Did a local version execution and make sure that prettier did get executed.

### CODE REVIEW

**Comment by iclanton** [comment]
I think it may make sense to make this behavior optional. Can we add a `--no-commit-hooks` flag to these commands to disable this new behavior?

**Comment by manrueda** [comment]
Sure, I will work on that.

**Comment by D4N14L** [comment]
FWIW, we already have a `--ignore-hooks` flag on install, would make sense to reuse that terminology here: https://github.com/microsoft/rushstack/blob/52d680e2aa165ca08ece65ca7fe65fa75c0dff45/apps/rush-lib/src/cli/actions/BaseInstallAction.ts#L82

**Comment by octogonz** [comment]
@D4N14L Any objections to merging this PR?

**Comment by D4N14L** [comment]
> @D4N14L Any objections to merging this PR?

@octogonz nope! LGTM.

**Comment by mikeechen** [comment]
Maybe we can make this available to include the push commands too? There are reasons to have push hooks, so why not just pass in `--ignore-hooks` to ignore all hooks in general? This will be especially useful in CI where we don't really want hooks to pass through? Also `git push --delete` command doesn't have the --no-verify flag with it, so maybe any git command under version we should just have this flag like `--ignore-hooks` as an option?

**Comment by D4N14L** [comment]
The main issue I have with that is that Rush hooks (post build/post install) should not be confused with Git hooks, since they are an entirely different concept. If anything, maybe the flag could be `--ignore-git-hooks` to differentiate while providing the increased functionality, but no strong opinion here. @octogonz?

**Comment by octogonz** [comment]
I agree with @mikeechen that the flag should apply to ALL Git commands invoked.

**Comment by mikeechen** [comment]
> The main issue I have with that is that Rush hooks (post build/post install) should not be confused with Git hooks, since they are an entirely different concept. If anything, maybe the flag could be `--ignore-git-hooks` to differentiate while providing the increased functionality, but no strong opinion here. @octogonz?

You have a point there where one flag is specifically for `rush` hooks, and another would be for git. I have no preference on naming, but your point makes sense for us to avoid using the same name. What if we just pass the `--no-verify` flag from rush to git when the flag is present? Won't that simplify the flags? We then won't really need to listen on custom flags right?

**Comment by manrueda** [comment]
@octogonz Agree with the rush hooks and git hooks differentiation. I will work later today in updating the PR with the rename and adding it to all git commands in the version process.

**Review by iclanton — APPROVED** [review]

**Pull request merged**
