### PR TITLE
[rush] Add support for pnpm ignoredOptionalDependencies

### LINKED ISSUE #4859: [rush] feature request: support pnpm's `ignoredOptionalDependencies` setting in pnpm-config.json
## Summary

pnpm has an [`ignoredOptionalDependencies` setting](https://pnpm.io/package_json#pnpmignoredoptionaldependencies) that is not yet supported by rush's pnpm-config.json

I would like to use it to ignore specific optional dependencies! 😄 

## Details

My specific use case is that I rely on a package (`fabric@5.3.0`) that has an optional dependency on `canvas`. For the way I'm using fabric, I don't need canvas. Moreover, `canvas` happens to be complicated to build on ARM linux. So, rather than going through the complication of getting `canvas` to build, I want to ignore that optional dependency, because I don't actually need it for the way I am using `fabric`.

As a workaround, I can use the existing `globalNeverBuiltDependencies` feature. But this isn't great, because if I someday add another dependency that _requires_ canvas (as a regular dependency), it will be installed, but its build will be skipped and it will be really non-obvious why my code isn't working.

## Standard questions

Please answer these questions to help us investigate your issue more quickly:

| Question | Answer |
| -------- | -------- |
| `@microsoft/rush` globally installed version? | 5.131.0 |
| `rushVersion` from rush.json? | 5.131.0 |
| `useWorkspaces` from rush.json? | true |
| Operating system? | all |
| Would you consider contributing a PR? | yes, but I don't know how to test for problems this change would cause |
| Node.js version (`node -v`)? | 20.15.1 |

### PR DESCRIPTION
**Pull request by glitchkyle**
## Summary

Fixes #4859

Changes include updating pnpm configuration to use pnpm's `ignoredOptionalDependencies` setting. End-user should now be able to specify optional dependencies in `common/config/rush/pnpm-config.json` in case some optional dependencies are required at a later point.

## Details

Changes focused on updating the `rush init` template and having`ignoredOptionalDependencies` in `common/temp/package.json` copied from `common/config/rush/pnpm-config.json`. Changes might not fully reflect until schema changes and `rushVersion` are updated after merging this PR.

## How it was tested

1. Ran `rush init` (when I had the schema changed in `common/config/rush/pnpm-config.json`) to check if `common/config/rush/pnpm-config.json` contained newly added field `globalIgnoredOptionalDependencies`
2. Ran `rush update` with local build after adding `fsevents` in `globalIgnoredOptionalDependencies` to see if `fsevents` was in `common/temp/package.json`

## Impacted documentation

PR might affect `pnpm-config.json` schema (https://rushjs.io/pages/configs/pnpm-config_json/)

### CODE REVIEW

**Comment by glitchkyle** [comment]
@microsoft-github-policy-service agree

**Comment by glitchkyle** [comment]
Making a draft PR for now while waiting for response on [Zullipchat](https://rushstack.zulipchat.com/#narrow/stream/279883-contributor-helpline/topic/Testing.20Rush.20changes) regarding testing changes and how to fix failing CI.

**Review by D4N14L — APPROVED** [review]
@glitchkyle it looks like your description mentions updating the `rush init` template, but I don't see any changes relating to that. Were they missed?

**Comment by glitchkyle** [comment]
> @glitchkyle it looks like your description mentions updating the `rush init` template, but I don't see any changes relating to that. Were they missed?

I could be wrong here but I thought the `pnpm-config.json` that contains the `rush init` template will be changed once the `rushVersion` is also updated.

Should be a quick change though by adding `globalIgnoredOptionalDependencies` in `libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json`.

**Comment by D4N14L** [comment]
> > @glitchkyle it looks like your description mentions updating the `rush init` template, but I don't see any changes relating to that. Were they missed?
> 
> I could be wrong here but I thought the `pnpm-config.json` that contains the `rush init` template will be changed once the `rushVersion` is also updated.
> 
> Should be a quick change though by adding `globalIgnoredOptionalDependencies` in `libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json`.

@glitchkyle yes you'll need to manually update the template. It's not updated as a part of any auto-generation process.... though that would be nice.

**Review by D4N14L — APPROVED** [review]

**Pull request merged**
